apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-4-oct25
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/test-4-oct25:ecaa80eb3a588317ac08f86c7cdc7d915ff57a2e@sha256:d286126c46942600df9f62953414e84f4abf049ef8ba914ae99a83f97eb5e5bb # use pre-built to bootstrap 
          name: app-inference
